### ISSUE TITLE
extract bootId from USN

### ISSUE THREAD

**Issue by sproctor** [ivanempire/lighthouse#17]
Per the spec " the same BOOTID.UPNP.ORG field value shall be used in all announcements, search responses, update messages and eventually bye-bye messages."

Somewhat related, I think `EmbeddedDevice` and `EmbeddedService` should be siblings of `AbridgedMediaDevice` and UniqueServiceName should be internal. Implementing that basically just makes two copies of the class that need to have 1:1 mappings. I'll leave that to you if you agree.

**Comment by ivanempire** [comment]
Fine with the `bootId` and the `internal` change, but can you elaborate more on the siblings bit? Also as an FYI I'm not with testing equipment for a bit, so next time I'll have a chance to properly test everything, and make a new release will be in a couple of weeks at least.

**Comment by sproctor** [comment]
`EmbeddedDevice` and `EmbeddedService` are a similar type of thing as `AbridgedMediaDevice`, kind of.

The protocol is quite strange. The root device is supposed to have a device type, but there doesn't appear to be any way to associate that with the root device without querying the XML endpoint since it's sent in a separate message.

Maybe they shouldn't be siblings with `AbridgedMediaDevice` in this case. `EmbeddedDevice` is also be a bit of a misnomer, since the list of embedded devices actually contains the root device type, but that's a bit pedantic. Also, the devices and services list exposed by the API wouldn't need to include the `uuid` since it's required to be the same as the containing `AbridgedMediaDevice`.
