### ISSUE TITLE
mavenCentral build broken?

### ISSUE THREAD

**Issue by kamnxt** [ivanempire/lighthouse#26]
Hi!
I was trying to include Lighthouse in a small project but couldn't get Android Studio to find it. After a few red herrings (Android Studio managed to run out of RAM on my machine while first downloading it, leading me to think the issue could have been caused by a corrupt package in my local gradle cache), I realized including `implementation("com.ivanempire:lighthouse:1.2.1")` does work, but using version 2.0.0 or 2.1.0 doesn't.

Further looking into this, it seems like the issue is that the packages after 1.2.1 don't actually include the code properly? Compare [1.2.1](https://repo1.maven.org/maven2/com/ivanempire/lighthouse/1.2.1/) with [2.0.0](https://repo1.maven.org/maven2/com/ivanempire/lighthouse/2.0.0/) on maven central, specifically the sizes of the main `.aar` files, which went from 143k in 1.2.1 to 1.2k in 2.0.0, so obviously seems like something is missing.

**Comment by ivanempire** [comment]
Hey!
Thanks for raising this - let me take a look, just seeing this.

**Comment by ivanempire** [comment]
I noticed two things. In my Gradle rework I flipped minification settings on and that was the reason for the code getting stripped out. I did just publish `2.1.1` to Maven and that AAR looks good (I've inspected it locally before publishing).

However, I am having trouble with AS loading up older versions (like `1.0.0`) into the project, so I'm still debugging that.
