### ISSUE TITLE
Multiple `discoverDevices` flows from the same client modify eachother

### ISSUE THREAD

**Issue by sproctor** [ivanempire/lighthouse#27]
There's something just a bit off with this API. You can't monitor two different search requests concurrently in the same client, although the API would leave you to believe you could. I recommend either passing the `SearchRequest` in the builder instead of `discoverDevices`, or make the state local to the function `discoverDevices`.

Or change the API to something like:
```kotlin
interface LighthouseClient {
    val discoveredDevices: StateFlow<List<AbridgedMediaDevice>>

    fun startDiscovery(searchRequest: SearchRequest)
    fun stopDiscovery()
}
```

**Comment by ivanempire** [comment]
Yeah that's a good point (@ monitoring multiple requests), I'll most likely adjust the API. Thanks for the suggestion!
