### ISSUE TITLE
Re-starting a discovery causes a crash

### ISSUE THREAD

**Issue by sproctor** [ivanempire/lighthouse#31]
`java.lang.IllegalStateException: Discovery is already in progress - did you call discoverDevices() multiple times?`

`onCompletion` is never called from the demo.

Actually the stop button in the demo is enabled at the wrong time, but fixing that, hitting stop causes a hang, fixing that, causes a crash when it's restarted.

**Comment by ivanempire** [comment]
Thanks for filing this one - will be taking a look this week!
